In [1]:
# For data manipulation

import pandas as pd

import numpy as np 

# machine learning classification

from sklearn.svm import SVC

from sklearn.metrics import scorer

from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


# To plot
%matplotlib inline
import matplotlib.pyplot as plt

import seaborn

# To fetch data

#from pandas_datareader import data as pdr

In [14]:
import glob
import pandas as pd
pattern='*.csv'
hong = glob.glob(pattern)
len(hong)

58

In [20]:
hkong = pd.read_csv(hong[0])
hkong = hkong.drop('Adj Close', axis=1)
hkong.columns = ['Date', 'Open' + '_'+str(0), 'High'+'_'+str(0), 'Low' +'_'+str(0), 'Close'+ '_'+str(0), 'Volume'+ '_'+ str(0)]
hkong =hkong.fillna(0)
#for col in hkong:
#    hkong[col] = hkong[col].fillna(0)
#hkong['Target'] = np.where(hkong['Close'].shift(-1) > hkong['Close'],int(1),int(-1))
hkong.shape

(1234, 6)

In [21]:
hkong['Open' + '_'+str(0)] = ((hkong['Open' + '_'+str(0)] - hkong['Open' + '_'+str(0)].shift(1))/hkong['Open' + '_'+str(0)].shift(1)) *100

hkong['High' + '_'+str(0)] = ((hkong['High' + '_'+str(0)] - hkong['High' + '_'+str(0)].shift(1))/hkong['High' + '_'+str(0)].shift(1)) *100

hkong['Low' + '_'+str(0)] = ((hkong['Low' + '_'+str(0)] - hkong['Low' + '_'+str(0)].shift(1))/hkong['Low' + '_'+str(0)].shift(1)) *100

hkong['Close' + '_'+str(0)] = ((hkong['Close' + '_'+str(0)] - hkong['Close' + '_'+str(0)].shift(1))/hkong['Close' + '_'+str(0)].shift(1)) *100

hkong = hkong.drop(0, axis=0)


print hkong.shape
hkong.head()

#hkong['Open' + '_'+str(0)] = hkong['Open' + '_'+str(0)].drop(hkong['Open' + '_'+str(0)].index[0])

(1233, 6)

        Date    Open_0    High_0     Low_0   Close_0  Volume_0
1  3/12/2013 -0.776397 -0.613485  0.315451  0.469474   1597412
2  3/13/2013 -0.469490 -0.925938 -2.830186 -3.115259   2922548
3  3/14/2013 -3.930818 -2.336443 -1.294498 -0.321543   2704634
4  3/15/2013  3.600658  1.754386  1.147541 -0.161287   3487274
5  3/18/2013 -2.843602 -2.351097 -1.620746  0.646200   2427267

In [22]:
#run only once
for i in range(1,len(hong)):
    df = pd.read_csv(hong[i]) 
    
    df = df.drop('Adj Close', axis=1)  
    
    df = df.fillna(0)
      
    df.columns = ['Date', 'Open' + '_'+str(i), 'High'+'_'+str(i), 'Low' +'_'+str(i), 'Close'+'_'+str(i), 'Volume'+'_'+str(i)]
    
    
    #for col in df:
     #   df[col] = df[col].fillna(0)
    
    df['Open' + '_'+str(i)] = ((df['Open' + '_'+str(i)] - df['Open' + '_'+str(i)].shift(1))/df['Open' + '_'+str(i)].shift(1)) *100

    df['High' + '_'+str(i)] = ((df['High' + '_'+str(i)] - df['High' + '_'+str(i)].shift(1))/df['High' + '_'+str(i)].shift(1)) *100

    df['Low' + '_'+str(i)] = ((df['Low' + '_'+str(i)] - df['Low' + '_'+str(i)].shift(1))/df['Low' + '_'+str(i)].shift(1)) *100

    df['Close' + '_'+str(i)] = ((df['Close' + '_'+str(i)] - df['Close' + '_'+str(i)].shift(1))/df['Close' + '_'+str(i)].shift(1)) *100

    df = df.drop(0, axis=0)
    
    hkong = pd.merge(hkong, df, how='outer', on='Date')

#for col in hkong.columns:
#    hkong[col] = hkong[col].fillna(0)
hkong = hkong.fillna(0)
hkong.shape

(1555, 291)

In [18]:
hkong.head(25)

,Date,Open_0,High_0,Low_0,Close_0,Volume_0,Open_1,High_1,Low_1,Close_1,...,Open_56,High_56,Low_56,Close_56,Volume_56,Open_57,High_57,Low_57,Close_57,Volume_57
0,3/12/2013,-0.776397,-0.613485,0.315451,0.469474,1597412.0,1.754380,0.143882,0.441182,-0.436673,...,-0.238700,0.531070,-1.382659,-1.038177,117600.0,0.213418,-0.321168,-0.190709,-0.547478,2738000.0
1,3/13/2013,-0.469490,-0.925938,-2.830186,-3.115259,2922548.0,-0.574716,-0.574716,-1.903373,-0.877190,...,-1.168739,-2.012475,-0.511300,-0.989981,91000.0,-0.250032,-0.194338,-0.302631,0.010004,2224400.0
2,3/14/2013,-3.930818,-2.336443,-1.294498,-0.321543,2704634.0,-1.589593,-1.589593,0.149251,0.294979,...,-1.156576,-0.442113,0.002709,0.278674,80200.0,-0.205514,-0.557313,-0.202575,-0.547182,2150200.0
3,3/15/2013,3.600658,1.754386,1.147541,-0.161287,3487274.0,1.321589,2.349483,1.639341,1.470588,...,0.600239,1.575284,-0.146681,0.357832,116400.0,-0.159327,-0.034864,-0.268680,-0.305210,2530400.0
4,3/18/2013,-2.843602,-2.351097,-1.620746,0.646200,2427267.0,-1.449275,-2.439019,-2.785912,-3.333339,...,-0.089359,-1.558245,-0.479589,-1.684724,93200.0,-1.288914,-1.397011,-1.480517,-1.465160,2031400.0
5,3/19/2013,0.650410,-0.160514,0.494234,-1.605136,3164000.0,-2.941176,-0.882350,-0.452495,0.149937,...,-1.015408,-0.647441,-0.321147,0.777582,87600.0,-0.548008,-0.309199,0.207492,0.347320,1804200.0
6,3/20/2013,-0.484659,3.697749,0.819672,4.730825,3876986.0,1.060600,0.000000,0.454552,0.000000,...,0.600293,2.500588,1.137846,2.655268,131200.0,-0.111433,-0.244539,-0.476111,-0.515922,1954200.0
7,3/21/2013,4.707796,2.015510,0.162598,-2.647969,5364256.0,0.899562,0.445095,0.754148,0.898201,...,2.678258,0.558829,2.400223,0.296324,119200.0,-0.073771,-0.017590,0.324659,0.177097,1695800.0
8,3/22/2013,-1.395352,-2.127662,1.136367,2.400000,2939218.0,1.040113,1.033982,0.449093,-0.148365,...,0.137951,0.050717,0.145527,0.173654,101200.0,-0.222637,-0.134771,-0.199948,-0.199948,1727200.0
9,3/25/2013,0.628934,1.863348,1.605136,0.937497,2942187.0,1.323532,0.730994,0.745157,0.594342,...,0.574309,0.553128,0.213434,-0.067131,97000.0,0.653651,0.567628,0.747157,0.768320,1806800.0
10,3/26/2013,0.625003,3.353668,1.737760,3.715173,7810269.0,-1.451379,-1.451379,-1.627216,-0.443123,...,-0.692037,-1.062138,-1.672051,-1.248376,104400.0,0.141431,-0.004692,-0.113441,0.003052,1850200.0
11,3/27/2013,6.055904,8.849557,5.279506,8.208955,8645038.0,-0.441832,0.883649,0.751880,1.186935,...,-0.828134,0.150389,0.345322,0.156292,96400.0,-0.012068,0.223185,0.149891,0.480633,1851200.0
12,3/28/2013,6.442155,3.794030,6.194684,2.896549,9376933.0,0.739645,-0.583945,0.149251,-0.293249,...,-1.123128,-2.148721,-2.450381,-2.822715,127600.0,0.418659,0.145045,-0.158833,-0.345070,1813200.0
13,4/2/2013,2.613483,-1.697120,-0.416672,-2.144769,4957545.0,-0.146840,0.440535,-0.149028,0.441182,...,0.244046,0.422153,-0.308668,-0.297845,89800.0,-0.467465,-0.167176,-0.215537,0.176472,1638000.0
14,4/3/2013,-2.144769,0.929610,1.813116,2.191778,7117899.0,2.352938,1.754380,1.641788,0.732064,...,-0.098742,-0.536110,-0.143531,-0.109756,81800.0,0.657958,0.374662,0.434291,0.368625,1919600.0
15,4/5/2013,2.191778,-1.842108,-0.958899,-1.474528,9897750.0,-1.149417,-1.149417,-4.258447,-4.215119,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,4/8/2013,-1.876678,1.340483,0.414929,1.496596,2961865.0,-4.360465,-4.360465,-0.613485,-0.758725,...,-1.632828,-1.282900,-1.649738,-0.615778,86200.0,-1.483182,-1.396124,-2.101398,-2.386700,2561600.0
17,4/9/2013,1.092902,0.264558,-0.688705,-0.938332,6569901.0,-0.303960,0.759878,0.925923,0.152902,...,0.875543,1.000601,1.595560,0.641252,82800.0,-0.824905,-0.790124,-0.420009,-0.312791,1888800.0
18,4/10/2013,1.621616,3.298153,2.496538,4.871445,4713740.0,-0.304872,-0.754148,-0.611624,-0.305337,...,0.427316,-0.075403,-0.131169,0.015817,80600.0,0.081504,-0.105122,0.324825,0.313898,1736400.0
19,4/11/2013,3.324468,0.766281,0.135315,-2.580645,8628500.0,2.293578,1.975675,1.384618,1.684530,...,0.541536,0.422696,0.212598,-0.295266,73600.0,0.201080,1.093919,0.627777,1.356673,1842000.0
20,4/12/2013,-2.574003,-1.647660,1.891895,2.119203,4797996.0,-0.448436,-0.149028,0.303484,0.000000,...,-0.844393,-0.723175,-0.578501,-0.575474,66800.0,0.931364,0.087553,0.281951,-0.462588,1677600.0
21,4/15/2013,0.132111,0.257740,0.530507,0.518809,5936500.0,-1.051045,-1.343287,-1.361576,-1.506024,...,-0.819620,-0.955633,-1.227072,-1.125582,71600.0,-0.582618,-0.378134,-0.733622,-0.742813,1634200.0
22,4/16/2013,0.263847,-0.642673,-0.923491,-0.645161,3885500.0,-2.276176,-1.664142,-1.840485,-1.376150,...,-1.376607,-0.387992,-0.532932,0.591402,80000.0,-1.591869,-0.434841,-0.833459,0.483286,1548000.0
23,4/17/2013,1.710532,0.517454,0.932099,-0.779218,3404824.0,1.086950,1.692305,0.781250,0.465122,...,1.170803,0.048996,0.585703,-0.047797,68400.0,1.715010,0.278940,1.338467,0.102807,1906600.0
24,4/18/2013,-3.234152,-3.603596,-3.298153,-3.403139,9146955.0,0.307229,-0.907713,-0.155036,-0.154333,...,-0.601812,0.387668,-0.138854,0.173496,71600.0,-0.528328,0.042438,-0.438934,-0.226912,1784600.0

In [23]:

hkong.isnull().sum()[hkong.isnull().sum() !=0]

Series([], dtype: int64)

In [24]:
for i in range(30):
    hkong['Open'+'_'+str(i)+str(-1)] = hkong['Open'+'_'+str(i)].shift(1)
    hkong['Open'+'_'+str(i)+str(-2)] = hkong['Open'+'_'+str(i)].shift(2)
    hkong['Open'+'_'+str(i)+str(-3)] = hkong['Open'+'_'+str(i)].shift(3)
    hkong['Open'+'_'+str(i)+str(-4)] = hkong['Open'+'_'+str(i)].shift(4)
    hkong['Open'+'_'+str(i)+str(-5)] = hkong['Open'+'_'+str(i)].shift(5)
    
    hkong['High'+'_'+str(i)+str(-1)] = hkong['High'+'_'+str(i)].shift(1)
    hkong['High'+'_'+str(i)+str(-2)] = hkong['High'+'_'+str(i)].shift(2)
    hkong['High'+'_'+str(i)+str(-3)] = hkong['High'+'_'+str(i)].shift(3)
    hkong['High'+'_'+str(i)+str(-4)] = hkong['High'+'_'+str(i)].shift(4)
    hkong['High'+'_'+str(i)+str(-5)] = hkong['High'+'_'+str(i)].shift(5)
    
    hkong['Low'+'_'+str(i)+str(-1)] = hkong['Low'+'_'+str(i)].shift(1)
    hkong['Low'+'_'+str(i)+str(-2)] = hkong['Low'+'_'+str(i)].shift(2)
    hkong['Low'+'_'+str(i)+str(-3)] = hkong['Low'+'_'+str(i)].shift(3)
    hkong['Low'+'_'+str(i)+str(-4)] = hkong['Low'+'_'+str(i)].shift(4)
    hkong['Low'+'_'+str(i)+str(-5)] = hkong['Low'+'_'+str(i)].shift(5)
    
    hkong['Close'+'_'+str(i)+str(-1)] = hkong['Close'+'_'+str(i)].shift(1)
    hkong['Close'+'_'+str(i)+str(-2)] = hkong['Close'+'_'+str(i)].shift(2)
    hkong['Close'+'_'+str(i)+str(-3)] = hkong['Close'+'_'+str(i)].shift(3)
    hkong['Close'+'_'+str(i)+str(-4)] = hkong['Close'+'_'+str(i)].shift(4)
    hkong['Close'+'_'+str(i)+str(-5)] = hkong['Close'+'_'+str(i)].shift(5)
    
    hkong['Volume'+'_'+str(i)+str(-1)] = hkong['Volume'+'_'+str(i)].shift(1)
    hkong['Volume'+'_'+str(i)+str(-2)] = hkong['Volume'+'_'+str(i)].shift(2)
    hkong['Volume'+'_'+str(i)+str(-3)] = hkong['Volume'+'_'+str(i)].shift(3)
    hkong['Volume'+'_'+str(i)+str(-4)] = hkong['Volume'+'_'+str(i)].shift(4)
    hkong['Volume'+'_'+str(i)+str(-5)] = hkong['Volume'+'_'+str(i)].shift(5)

hkong = hkong.fillna(0)
hkong.shape

(1555, 1041)

In [25]:
for i in range(30):
    hkong['Target'+'_'+str(i)] = np.where(hkong['Close'+'_'+str(i)]>0.5,1,0)
    
hkong.shape

(1555, 1071)

In [10]:
hkong.head()

,Date,Open_0,High_0,Low_0,Close_0,Volume_0,Open_1,High_1,Low_1,Close_1,...,Target_20,Target_21,Target_22,Target_23,Target_24,Target_25,Target_26,Target_27,Target_28,Target_29
0,3/12/2013,-0.776397,-0.613485,0.315451,0.469474,1597412.0,1.754380,0.143882,0.441182,-0.436673,...,0,0,0,1,0,0,0,0,0,0
1,3/13/2013,-0.469490,-0.925938,-2.830186,-3.115259,2922548.0,-0.574716,-0.574716,-1.903373,-0.877190,...,0,0,0,0,0,0,0,0,0,0
2,3/14/2013,-3.930818,-2.336443,-1.294498,-0.321543,2704634.0,-1.589593,-1.589593,0.149251,0.294979,...,0,1,0,0,0,0,1,1,0,0
3,3/15/2013,3.600658,1.754386,1.147541,-0.161287,3487274.0,1.321589,2.349483,1.639341,1.470588,...,0,0,0,0,0,0,0,0,0,0
4,3/18/2013,-2.843602,-2.351097,-1.620746,0.646200,2427267.0,-1.449275,-2.439019,-2.785912,-3.333339,...,0,0,0,0,0,0,0,0,0,0

In [26]:
hkong.index = hkong.Date
hkong = hkong.drop('Date', axis=1)
hkong.shape

(1555, 1070)

In [27]:
hkong.head()

,Open_0,High_0,Low_0,Close_0,Volume_0,Open_1,High_1,Low_1,Close_1,Volume_1,...,Target_20,Target_21,Target_22,Target_23,Target_24,Target_25,Target_26,Target_27,Target_28,Target_29
Date,,,,,,,,,,,,,,,,,,,,,
3/12/2013,-0.776397,-0.613485,0.315451,0.469474,1597412.0,1.754380,0.143882,0.441182,-0.436673,23618156.0,...,0,0,0,1,0,0,0,0,0,0
3/13/2013,-0.469490,-0.925938,-2.830186,-3.115259,2922548.0,-0.574716,-0.574716,-1.903373,-0.877190,31644955.0,...,0,0,0,0,0,0,0,0,0,0
3/14/2013,-3.930818,-2.336443,-1.294498,-0.321543,2704634.0,-1.589593,-1.589593,0.149251,0.294979,21286152.0,...,0,1,0,0,0,0,1,1,0,0
3/15/2013,3.600658,1.754386,1.147541,-0.161287,3487274.0,1.321589,2.349483,1.639341,1.470588,44707880.0,...,0,0,0,0,0,0,0,0,0,0
3/18/2013,-2.843602,-2.351097,-1.620746,0.646200,2427267.0,-1.449275,-2.439019,-2.785912,-3.333339,38221257.0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
hkong.to_csv('E:/hkongpercent-5_zero.csv')